### ISSUE TITLE
como faço para rodar o código?

### ISSUE THREAD

**Issue by camilagaertner** [glaucia86/demos-playwright-e2e#3]
tentei rodar e não deu certo, primeiro eu dei no prompt do windows um "npm install" e depois "npm test" mas não deu nada sem ser isso: 
![image](https://user-images.githubusercontent.com/61475424/131168802-42c10aa5-26f3-4567-887c-9a89678c4fda.png)

**Comment by glaucia86** [comment]
Oi, @camilagaertner tudo bem?
Basta usar o comando:

```bash

> node <nome-do-arquivo>

````

Vou alterar depois isso, com o tempo! Obrigada pelo feedback!
